#game
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
#player
PLAYER_RADIUS = 20
PLAYER_SPEED = 200
PLAYER_TURN_SPEED = 300
SHOT_RADIUS = 5
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN_SECONDS = 0.3
PLAYER_HIT_COOLDOWN_SECONDS = 3
#drawing
LINE_WIDTH = 2
#asteroids
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
#score
SCORE_POSITION = (20, 20)
LIVES_POSITION = (20, 70)
SCORE_FONT_SIZE = 48
SCORES_FOR_ASTEROIDS = [0, 100, 50, 20]
EXTRA_LIFE_POINTS = 10000
#colors
COLOR_PLAYER = "magenta"
COLOR_SHOT = "green"
COLOR_ASTEROID = "white"